/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tyron;

import javax.swing.JOptionPane;

/**
 *
 * @author Tyron Jay
 */
public class Canteen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Canteen.class.getName());

    /**
     * Creates new form Canteen
     */
    public Canteen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblorder = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtchange = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txtcash = new javax.swing.JTextField();
        btnselect = new javax.swing.JButton();
        txtvat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(0, 255, 204));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("CANTEEN");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 52));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SNACKS");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("DRINKS");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("[1] Piatos P13.00");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("[5] Pop & Crunch P 12.00");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("[6] Coke P 25.00");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("[7] Royal P 20.00");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("[8] FruitJuice P 15.00");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("[4] Nibbly Nest P 8.00");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("[2] Nova P 15.00");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("[3] BiteBuzz P 10.00");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("[10] FizzPop P 10.00");
        panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("[9] RC P 7.00");
        jLabel13.setToolTipText("");
        panel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        panel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        panel2.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 40, 390));

        panel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panel2.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1040, 40));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 480));

        panel1.setBackground(new java.awt.Color(0, 204, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panel1.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("CHOOSE FROM THE MENU:");
        panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("QUANTITY:");
        panel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 30));

        lblorder.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblorder.setText("ORDER:");
        panel1.add(lblorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 190, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Tax 12%");
        panel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, 30));
        panel1.add(txtchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 120, 40));
        panel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 120, 40));
        panel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 120, 40));

        txtcash.setEnabled(false);
        txtcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcashActionPerformed(evt);
            }
        });
        panel1.add(txtcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 120, 40));

        btnselect.setBackground(new java.awt.Color(255, 255, 0));
        btnselect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnselect.setText("SELECT");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });
        panel1.add(btnselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 120, 40));
        panel1.add(txtvat, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 120, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Amount:");
        panel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("Change:");
        panel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 950, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        int x = Integer.parseInt(txt1.getText());
        int y = Integer.parseInt(txt2.getText());
        int v = Integer.parseInt(txtchange.getText());
        if (x == 1)
        {
        
        lblorder.setText("Piatos");
        
         int Piatos = 13;
         int results = y * Piatos;
         int change = v - results;
         double Vat = results * 0.12; 
         JOptionPane.showMessageDialog(null, "Your order: Piatos"
                 +"\n Price: P" + Piatos
                 + "\nQuantity:" + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P" + change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+ results);
         }
        else if(x == 2)
        {
         lblorder.setText("Nova");
        
         int Nova = 15;
         int results = y * Nova;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: NOVA"
                 +"\n Price: P" + Nova
                 + "\nQuantity: " + y 
                 + "\nTotal: P"+ results
                   + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }         
         txtcash.setText(""+results);
        
        }
        
        else if(x == 3)
        {
         lblorder.setText("BiteBuzz");
        
         int Bite = 10;
         int results = y * Bite;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: BiteBuzz"
                 +"\n Price: P" + Bite
                 + "\nQuantity: " + y 
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }         
         txtcash.setText(""+results);
        
        }
        
        else if(x == 4)
        {
         lblorder.setText("Nibbly Nest");
        
         int Nibbly = 8;
         int results = y * Nibbly;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: Nibbly Nest"
                 +"\n Price: P" + Nibbly
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
        
         else if(x == 5)
        {
         lblorder.setText("Pop & Crunch ");
        
         int Pop  = 12;
         int results = y * Pop;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: Pop & Crunch"
                 +"\n Price: P" + Pop
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
         
          else if(x == 6)
        {
         lblorder.setText("Coke");
        
         int Coke = 25;
         int results = y * Coke;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: Coke"
                 +"\n Price: P" + Coke
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
          
           else if(x == 7)
        {
         lblorder.setText("Royal");
        
         int Royal = 20;
         int results = y * Royal;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: Royal"
                 +"\n Price: P" + Royal
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
           
            else if(x == 8)
        {
         lblorder.setText(" FruitJuice ");
        
         int  FruitJuice = 15;
         int results = y *  FruitJuice;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: FruitJuice"
                 +"\n Price: P" + FruitJuice
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
            
          else if(x == 9)
        {
         lblorder.setText("RC");
        
         int RC = 10;
         int results = y * RC;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: RC"
                 +"\n Price: P" + RC
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
          
         else if(x == 10)
        {
         lblorder.setText(" FizzPop ");
        
         int  FizzPop = 10;
         int results = y *  FizzPop;;
         int change = v - results;
         double Vat = results * 0.12; 
          JOptionPane.showMessageDialog(null, "Your order: FizzPop"
                 +"\n Price: P" + FizzPop
                 + "\nQuantity: " + y
                 + "\nTotal: P"+ results
                 + "\nVat: P" + Vat
                 + "\nchange: P"+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         int choice = JOptionPane.showConfirmDialog(null, "do you want to change order", "receipt", JOptionPane.YES_NO_CANCEL_OPTION);
          
         if (choice == JOptionPane.YES_OPTION)
         {
         JOptionPane.showMessageDialog(null, "you can order again", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.NO_OPTION)
         {
         JOptionPane.showMessageDialog(null, "No More Orders", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         else if (choice == JOptionPane.CANCEL_OPTION)
         {
         JOptionPane.showMessageDialog(null, "CANCELED", "Receipt", JOptionPane.INFORMATION_MESSAGE);
         }
         txtcash.setText(""+results);
        
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Invalid Selection", "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnselectActionPerformed

    private void txtcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Canteen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblorder;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtchange;
    private javax.swing.JTextField txtvat;
    // End of variables declaration//GEN-END:variables
}
