/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tyron;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2~PC38
 */
public class T2 extends javax.swing.JFrame {

    /**
     * Creates new form T2
     */
    public T2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtchange = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        btnchange = new javax.swing.JButton();
        txtcash = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        btnselect = new javax.swing.JButton();
        lblorder = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CANTEEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 52));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SNUCKS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("DRINKS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("[1] Piatos P13.00");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("[2] Nova P 15.00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("[3] Coke P 25.00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("[4] Royal P 20.00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("CHOOSE FROM THE MENU:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("QUANTITY:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));
        getContentPane().add(txtchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 110, 30));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 110, 30));

        btnchange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnchange.setText("CHANGE");
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 90, 50));

        txtcash.setEnabled(false);
        txtcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcashActionPerformed(evt);
            }
        });
        getContentPane().add(txtcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 110, 30));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 110, 30));

        btnselect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnselect.setText("SELECT");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });
        getContentPane().add(btnselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 90, 50));

        lblorder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblorder.setText("ORDER:");
        getContentPane().add(lblorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 70, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Amount:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcashActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        int x = Integer.parseInt(txt1.getText());
        int y = Integer.parseInt(txt2.getText());
        
        if (x == 1) 
        {
        
        lblorder.setText("Piatos");
        
         int Piatos = 13;
        int results = y * Piatos;
        
         JOptionPane.showMessageDialog(null, "Your order is Piatos P"+results, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         txtcash.setText(""+results);
        
        }
        
        else if(x == 2)
        {
         lblorder.setText("Nova");
        
         int Nova = 15;
         int results = y * Nova;
        
         JOptionPane.showMessageDialog(null, "Your order is Nova P"+results, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         txtcash.setText(""+results);
        
        }
        
        else if(x == 3)
        {
         lblorder.setText("Coke");
        
         int Coke = 25;
         int results = y * Coke;
        
         JOptionPane.showMessageDialog(null, "Your order is Coke P"+results, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         txtcash.setText(""+results);
        
        }
        
        else if(x == 4)
        {
         lblorder.setText("Royal");
        
         int Royal = 20;
         int results = y * Royal;
        
         JOptionPane.showMessageDialog(null, "Your order is Royal P"+results, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
         txtcash.setText(""+results);
        
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Invalid Selection", "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnselectActionPerformed

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
        
        int x = Integer.parseInt(txtcash.getText());
        int y = Integer.parseInt(txtchange.getText());
        int change =  y - x;
        
        JOptionPane.showMessageDialog(null, "Change is "+change, "CANTEEN", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnchangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchange;
    private javax.swing.JButton btnselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblorder;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtchange;
    // End of variables declaration//GEN-END:variables
}
